version: '3.9'
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017
    environment:
      - MONGO_URL=mongodb://test:test@mongocont:27017/test?authSource=admin
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./prisma/migrations/0_init/migration.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=mercury01
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@exchange-nest.com
      PGADMIN_DEFAULT_PASSWORD: mercury01
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    restart: always
  api:
    image: node:18.19.0-alpine3.19
    command: sh -c "npm i && npm run start:pie"
    build: ./build/
    ports:
      - '5000:5000'
      - '3000:3000'
    working_dir: /home/exchangenest/
    volumes:
      - ./:/home/exchangenest/
    links:
      - mongo
      - postgres
